[package]
name = "gpush"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
futures-intrusive = "0.5.0"
image = "0.25.8"
lazy_static = "1.5.0"
pollster = "0.4.0"
regex = "1.12.2"
wgpu = "27.0.1"
